- components/LotSubmissionForm.js
- components/PassengerHome.js
- fireMethods/index.js
These are just minor changes to LotSubmissionForm, it still needs more updates.
// This thing still needs to navigate back to the home
// Also, consider moving the creation to the firemethods
> Improve lot submission form

- App.js
- components/DriverHome.js
- components/LotBanner.js
DriverHome now presents a LotBanner for each lot in firestore.
Main changes that still need to be implemented are (1) making the button actually do something. We should talk about how it should look before we work on it. (2) Styling, so that it looks nice. (3) Logic that understands whether or not you have a leading bid on a lot
> Driver home1

- fireMethods/index.js
Signup is better, but could definitely still require more changes if we change the schema
-
added and commented createLot function which will be used on the LotSubmissionForm. Also updated signup to better reflect the necesarry schema
-
the createLot function is to pull some of the logic out of the LotSubmissionForm
It might be good to add some of the error message type of stuff like we have in signup and login
> Minor Changes to Firemethods

- App.js
- components/Account.js
This is just the preliminary version, we'll want edit-ability (of some sorts) and obviously styling
> Account component shows user information to the logged in user

- App.js
- components/DriverHome.js
- components/LotBanner.js
- components/Signup.js
Made small change to driverHome to make working in LotBanner easier. Made changes in LotBanner, so that the button now communicates with firestore, updating the driverId of a Lot that a driver clicks the button for
Changes will still be need to be made as the structure of Lots is formalized etc.
> Updating lot banner button

- fireMethods/index.js
Just a few validations for the CreateLot firemethod.
It still hasn't actually been used yet.
> added some validations

- components/ViewPhotos.js
- components/uploadImage.js
- firestore.js
- package-lock.json
- package.json
There's a decent amount of junk in here that needs to be cleaned up, but I'd rather merge it and work on that later, since it's not breaking anything.
The image uploading should work, just check firebase storage tab.
I commented a proposal for changing how we access firebase extensions. We had a firestore file which was exporting firebase.firestore(), and then we were just calling firebase.auth() whenever we need it. But now that we're also going to be using firebase.storage().ref(), I'm thinking we could just a have a file called fire.js, which would export all three. Then in a file, you might do something like:
import { store, auth, imgStorageRef } from '../fire';
This will mean going and changing several lines from import firestore from '../firestore'; to something like the above.
In …
> Camera roll#4

- components/DriverRegistration.js
- components/ViewPhotos.js
- components/uploadImage.js
- fireMethods/index.js
- package-lock.json
- package.json
made very basic and unfinished version of DriverRegistration. Also updated the signup form to reflect the temporary way of seeing whether or not someone is allowed to drive: the canDrive property
It looks like the drawer is too messy right now for me to do the part about clicking on "Switch to ---", so we'll worry about that later.
> Driver registration 1

- components/LotBanner.js
- components/LotSubmissionForm.js
- components/ViewPhotos.js
LotBanners should now show a picture of the screenshot. 
Also, the way that photos are uploaded has been changed slightly to make it more organized
> Driver home disp imgs

- components/DriverHome.js
- components/Login.js
- components/LotBanner.js
- components/LotBannerWrapper.js
- package-lock.json
- package.json
run npm install
The LotBannerWrapper is a necessary component, because the countdown component will start over if you re-render it. For now, all lots are set to a 60 second timer. This will be easy to change (in DH, get the lot from firestore, send it LBW, where the number of ms on the timer is determined by subtraction from a new Date()).
Also for now, the only thing that happens when the timer expires is that the component hides.
> Lot timers

- components/LotBanner.js
- components/LotBannerWrapper.js
- components/LotSubmissionForm.js
- fireMethods/index.js
> second day

- App.js
- components/DriverHome.js
- components/DriverRegistration.js
- components/Login.js
- components/LotBannerWrapper.js
- components/Payment.js
- components/SideMenu.js
So leaving the code inside of Render works but render is being called so many times that its making to many queries and its messing up everything pretty much. So what i did was i invoked componentDidMount manually on handleSwitch. It is working atm. I tested it, nothing broke. Now i'm not quite sure if invoking componentDidMount is a bad idea? Also did a few other changes here and there
> switching driver/passenger works

- components/LotBanner.js
- fireMethods/index.js
The first bid only updates the driverId, but after that, all bids lower the offer by 25 cents. Also the offer is now a float, rather than a string
> drivers now update the price of a lot when they bid on it

- components/LotSubmissionForm.js
- components/ViewPhotos.js
Fixed the image selector, I think..
Also, made some changes to LotSubmissionForm, but not all of them. I still want some validations, etc for dropoff location. 
Also, I think it'd be neat if the offer (which currently just takes an integer) had a double wheel, like the apple clock has. One column for dollars, and one for cents. I've looked at the library we're using, and the way that they built the android date-picker (https://github.com/pinguinjkeke/react-native-wheel-datepicker/blob/master/src/date-picker.android.js) makes me think that the way to do it is the same: just have two pickers side-by-side and try to make it look like they're really just one.
> Fixing image selector

- components/LotBanner.js
Should be good.. Not really sure why it wasn't doing this already. I thought that we had written this?
> Images now download on LotBanner

- components/DriverHome.js
- components/Login.js
- components/LotBanner.js
- components/LotBannerWrapper.js
- fireMethods/index.js
> Adding history

- components/DrawerNavigator.js
- components/Login.js
> working on persistance, and proper initial routes

- components/LotBanner.js
- fireMethods/index.js
- functions/.eslintrc.json
- functions/index.js
- package-lock.json
- package.json
----------------
----------------
there's only one function for now, and it doesn't actually send push notifications..
Once we upgrade our firebase plan, it should actually work
if it does, then we can add the other function
----------------
please not the change to the scripts in the package.json..
exp was installed and is being used to start things, because there was an error, and this fixed it
as far as I can tell, it doesn't really make a difference
> Push notes 2

- components/Account.js
- components/DrawerNavigator.js
- components/DriverHome.js
- components/DriverRegistration.js
- components/GooglePlacesInput.js
- components/Help.js
- components/Login.js
- components/LotBanner.js
- components/LotBannerWrapper.js
- components/LotSubmissionForm.js
- components/MainScreen.js
- components/MatchBanner.js
- components/Payment.js
- components/SideMenu.js
- components/Signup.js
- components/ViewPhotos.js
- components/Waiver.js
- components/Web.js
- components/Welcome.js
- components/Winner.js
- fire.js
- fireMethods/index.js
- functions/index.js
> all sorts cleaning going on

- components/Account.js
- components/DriverRegistration.js
- components/Login.js
> fixing more queries

- components/LotSubmissionForm.js
> fixed typo

- components/LotBanner.js
- components/MatchBanner.js
> Warning fixes

- components/DriverHome.js
- components/MainScreen.js
Some fixes.. There still seems to be a problem of some sort with DriverHome and Winner.js
> more fixes to queries

- functions/index.js
Just added the second cloud function.
Note that neither of these works yet (because of the firebase plan that we're on)
> fleshing out the functions

- components/LotBanner.js
- fireMethods/index.js
> Minor fixes

- components/Winner.js
- package-lock.json
- package.json
has not been tested, but we should be able to make phone calls in Winner
> Making phone calls

- components/MatchBanner.js
Phone calls have also been tested, and work!!
> phone calls now work on match banner as well. Very cool!

- components/History.js
Needs some real style, and probably some better arrangement/layout..
> History updates

- components/SideMenu.js
Tested it out, and it seems to all be working, for now.
I had thought that there was more to change, but I guess not?
> Home navigation works

- components/LotBanner.js
- components/SideMenu.js
- public/style.js
some styling, but whatever, very big problem:
> Updating styles

- components/LotBanner.js
- components/LotBannerWrapper.js
- components/LotSubmissionForm.js
- components/MatchBanner.js
- components/SideMenu.js
- components/Winner.js
- public/style.js
> More style

- components/DriverRegistration.js
- components/Help.js
- components/LotBanner.js
- components/LotBannerWrapper.js
- components/LotSubmissionForm.js
- components/MatchBanner.js
- components/SideMenu.js
- components/ViewPhotos.js
- components/Web.js
- components/Winner.js
- public/style.js
Please note the layout of the stylesheet (just grouping together things)..
Also, please check the note in LotBanner:
"THIS NEEDS TO BE MOVED, BUT I DON'T WANT TO BREAK ANYTHING SO, I'M LEAVING IT FOR NOW"
> Moar style

- functions/index.js
Push Notifications have been updated to be nicer. However, we still need to look into the issue of returning undefined, and if we really need to be returning something
> Push note updates

- components/DriverHome.js
- components/LotBannerWrapper.js
- components/MatchBanner.js
- components/Winner.js
- public/style.js
> Style 9 6 2

- components/GoogleDropoff.js
- components/GooglePickup.js
- components/LotBanner.js
- components/LotSubmissionForm.js
- components/ViewPhotos.js
renamed the file as well. I think two of those files are not necessary and can be fixed as one but for now its okay. will come back to it eventually
> cleaned the dropoff and pickup location

- components/DrawerNavigator.js
- components/Winner.js
> Winner is not very good, but I think it works

- components/DriverHome.js
- components/Winner.js
> Emergency1

- components/LotBanner.js
- public/style.js
> Formatting lot banner

- components/DriverRegistration.js
- components/LotSubmissionForm.js
- fireMethods/index.js
Changes to backend , and small changes to frontend about car types. This is meant to mirror UberX, UberXL, UberBlack, etc.
My thought is that drivers will be able to confirm what kind of car they have and if they qualify for one/both in the same way that Uber/Lyft does (I don't really know). Then, when a user submits a lot with a specification, drivers can only bid on it if they have the correct kind of car.
> Car types 1

- App.js
- components/DriverHome.js
- components/GoogleDropoff.js
- components/GooglePickup.js
- components/Login.js
- components/LotBanner.js
- components/LotBannerWrapper.js
- components/LotSubmissionForm.js
- components/MainScreen.js
- components/SideMenu.js
- components/Signup.js
- components/Waiver.js
- components/Welcome.js
- public/style.js
Lots of stuff for you to review
> Style 9 11 1

- components/LotSubmissionForm.js
- components/MainScreen.js
- components/SideMenu.js
- public/style.js
The logic for the button on Main Screen is based on from the users state 'currentLot' meaning that when a lot expires the currentLot on the users state needs to be deleted as well which is not right now. We didnt do that as we're thinking the lot expiration function is gonna have to change eventually. right?
> added restrictions

- components/Winner.js
winner should now be a little nicer
> Completing rides

- components/DriverHome.js
- components/LotBanner.js
- components/LotBannerWrapper.js
- components/LotSubmissionForm.js
- components/MainScreen.js
- components/MatchBanner.js
- components/ViewPhotos.js
HandleFinish in LotBannerWrapper needs to be fixed.. It's very bad..
> Janitorial services

- components/MatchBanner.js
- package-lock.json
- public/style.js
> styled matchbanner... nice

- components/Account.js
- components/MainScreen.js
> Account improvements

- components/Account.js
- components/MainScreen.js
I'm going to go ahead and merge this, as I want to have an up-to-date version
> More account improvements

- components/LotBannerWrapper.js
- fireMethods/index.js
For now, just read over this, and see how things are. Once you understand the situation, we can tackle it together
> made comments about what should be done about expiring lots

- components/MainScreen.js
- components/TripReceipt.js
- components/Winner.js
- fireMethods/index.js
Please review carefully; I touched a lot of files
> Trip receipt

- components/Account.js
- components/DriverHome.js
- components/DriverRegistration.js
- components/DropPin.js
- components/GoogleDropoff.js
- components/GooglePickup.js
- components/Help.js
- components/History.js
- components/Login.js
- components/LotBanner.js
- components/LotBannerWrapper.js
- components/LotSubmissionForm.js
- components/MainScreen.js
- components/MatchBanner.js
- components/Payment.js
- components/Signup.js
- components/ViewPhotos.js
- components/Waiver.js
- components/Web.js
- components/Winner.js
- fireMethods/index.js
Most of these changes are simple, but some are more complicated, so please review those. If you try to merge both of these PR's, there might be merge conflict (I don't actually know), but if there is, it should be easy to fix
> much cleaning

- components/Winner.js
Haven't actually tested this out, but I think that this is what we want
> winner should be doing better now

- components/Account.js
- components/LotBanner.js
- components/LotBannerWrapper.js
- components/SideMenu.js
- public/style.js
> stylin account finished for now

- components/DriverHome.js
- components/MainScreen.js
- components/MatchBanner.js
- components/Winner.js
It's definitely not finished, but I'm done for now..
I hope that navigating to winner works properly, and also the functionality of winner. The transmission of location to MatchBanner & MainScreen makes it as far as FireStore. However, MatchBanner and MainScreen Reading it or doing anything are nonexistent..
> Winner location

- components/Help.js
How to open a webpage the nice way..
> hope this works.. should be able to open webpages nicesly

- app.json
- components/DropPin.js
- components/Login.js
- components/LotSubmissionForm.js
- components/MainScreen.js
- components/MatchBanner.js
- components/Signup.js
- fireMethods/index.js
I'm not actually sure that either of these fixes work. @BryanEdison can you pull and test them out sometime? 😄 
2 things I'm thinking about/not sure about:
(1) I don't know if `react-native link` necessarily means that we can't use a library..
(2) I'm wondering if nativeBase is giving us problems. I switched out some of the NativeBase <Text> tags with ones from react-native, and it fixed that weird Roboto_medium font error
> Android fixes

- components/DriverHome.js
- fireMethods/index.js
- functions/index.js
Not totally finished yet.
DriverHome line 37 needs to be not hardcoded.. I believe that we want to use the reverse geocoder, but waiting, because I don't really know how that works (why do we have initialize it so much?)
> Sorting lots

- app.json
- components/SideMenu.js
fixed issues with Beta; hopefully fixed issues with location permissions; did not fix issues with Google Maps
The Map one is likely going to be troublesome... I think it might have something to do with the API key we use, but I'm not sure. The whole API key situation is very confusing and messy
> Fix apple problems

- components/Beta.js
- components/DriverRegistration.js
- components/LotSubmissionForm.js
- components/MainScreen.js
- components/SideMenu.js
I fixed the location permission notification message, and I got rid of things that I thought would create a problem. After re-submitting, it seems that the problem is that no buttons appear on MainScreen. (the `Where to?` button should appear). I have no idea why this might be happening...
I think that the best thing to do will be to add all sorts of stuff (like several kinds of buttons), and submit it that way to see what works. If it gets rejected because we have two buttons or something, then that's fine, but w/e.
> more fixes for App store -- still not functional :(

- app.json
- components/MainScreen.js
> Trying 2 fix main button
